# Default Profile

# Server Configuration
server.port=8080
server.address=0.0.0.0

# JPA Common Settings
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true

# Liquibase Common Settings
spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml

app.keycloak.base-url=${KEYCLOAK_BASE_URL:http://localhost:7070}
app.keycloak.realm=${KEYCLOAK_REALM:productivity-app}
app.keycloak.password-verification-client-id=${KEYCLOAK_PASSWORD_VERIFICATION_CLIENT_ID:admin-cli}
app.keycloak.admin.realm=${KEYCLOAK_ADMIN_REALM:master}
app.keycloak.admin.client-id=${KEYCLOAK_ADMIN_CLIENT_ID:admin-cli}
app.keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
app.keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:adminpassword}
